### ISSUE TITLE
Pre-trained model links have expired

### ISSUE THREAD

**Issue by arunesh** [formiel/speech-translation#1]
Hi there,

 Any chance of providing fresh links to the pretrained models ?

Thanks.

**Comment by formiel** [comment]
Hi @arunesh,

Thanks for reporting the issue! I will update the links shortly.

**Comment by formiel** [comment]
@arunesh The links have been updated. Sorry again for the inconvenience. I'm closing this issue. Please feel free to reopen it or create a new one if you encounter any problems in using the code.

**Comment by arunesh** [comment]
Hi @formiel 

Thanks so much !
